package jdm.mybatis.generator.dao;

import java.util.List;
import jdm.mybatis.generator.entity.Pet;
import jdm.mybatis.generator.entity.PetExample;
import org.apache.ibatis.annotations.Param;

public interface PetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    long countByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    int deleteByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    int insert(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    int insertSelective(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    List<Pet> selectByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    Pet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") Pet record, @Param("example") PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    int updateByExample(@Param("record") Pet record, @Param("example") PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    int updateByPrimaryKeySelective(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    int updateByPrimaryKey(Pet record);
}