package jdm.mybatis.generator.entity;

public class Pet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pets.id
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pets.name
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pets.master_id
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    private Integer masterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pets.id
     *
     * @return the value of pets.id
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pets.id
     *
     * @param id the value for pets.id
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pets.name
     *
     * @return the value of pets.name
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pets.name
     *
     * @param name the value for pets.name
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pets.master_id
     *
     * @return the value of pets.master_id
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    public Integer getMasterId() {
        return masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pets.master_id
     *
     * @param masterId the value for pets.master_id
     *
     * @mbg.generated Fri Sep 25 03:03:47 CST 2020
     */
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }
}